# Generated by Django 5.2.15 on 2026-06-26 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_url', models.URLField(max_length=512)),
                ('raw_body', models.JSONField()),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('parse_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='rates_rawre_fetched_b5a8f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(db_index=True, max_length=64)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('ingestion_ts', models.DateTimeField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='rates.provider')),
                ('raw_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='rates.rawresponse')),
            ],
            options={
                'ordering': ['-effective_date', '-ingestion_ts'],
                'indexes': [models.Index(fields=['provider', 'rate_type', '-effective_date'], name='rates_rate_provide_b549d0_idx'), models.Index(fields=['provider', 'rate_type', 'effective_date'], name='rates_rate_provide_c9b0b9_idx'), models.Index(fields=['-ingestion_ts'], name='rates_rate_ingesti_d7eb02_idx'), models.Index(fields=['ingestion_ts'], name='rates_rate_ingesti_a1f9eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'rate_type', 'effective_date', 'ingestion_ts'), name='unique_rate_snapshot')],
            },
        ),
    ]
